import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/Home.module.css";
import { useTodos } from "./useTodos";

const Header = () => {
  return (
    <div>
      <p>id</p>
      <p>title</p>
      <p></p>
    </div>
  );
};

const AddTodo = ({ hookTodos }) => {
  return (
    <div>
      <input ref={hookTodos.todoTitleRef} />
      <button onClick={hookTodos.addTodo}> add Todo </button>
    </div>
  );
};

const Todos = ({ hookTodos }) => {
  return (
    <div className="todos">
      <Header />
      {hookTodos.todos.map((todo) => (
        <div key={todo.id}>
          <p>{todo.id}</p>
          <button
            style={{ textDecoration: todo.done ? "line-through" : "none" }}
            onClick={() => hookTodos.toggleTodo(todo.id)}
          >
            {todo.title}
          </button>
          <button onClick={() => hookTodos.removeTodo(todo.id)}>╳</button>
        </div>
      ))}
    </div>
  );
};

export default function Home() {
  const hookTodos = useTodos();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Todos</h1>
        <AddTodo hookTodos={hookTodos} />
        <Todos hookTodos={hookTodos} />
      </main>
    </div>
  );
}
